- .github/workflows/feature.yml
- backend/Dockerfile
- backend/src/main/java/dev/be/dorothy/common/CommonResponse.java
- backend/src/main/java/dev/be/dorothy/config/AuthConfig.java
- backend/src/main/java/dev/be/dorothy/exception/BadRequestException.java
- backend/src/main/java/dev/be/dorothy/exception/InternalServerErrorException.java
- backend/src/main/java/dev/be/dorothy/member/Member.java
- backend/src/main/java/dev/be/dorothy/member/controller/MemberController.java
- backend/src/main/java/dev/be/dorothy/member/repository/MemberRepository.java
- backend/src/main/java/dev/be/dorothy/member/service/MemberResDto.java
- backend/src/main/java/dev/be/dorothy/member/service/MemberService.java
- backend/src/main/java/dev/be/dorothy/member/service/MemberServiceImpl.java
- backend/src/main/java/dev/be/dorothy/member/service/MemberSignUpValidator.java
- backend/src/main/java/dev/be/dorothy/member/service/MemberSignUpValidatorImpl.java
- backend/src/main/java/dev/be/dorothy/member/service/PasswordEncryptor.java
- backend/src/main/java/dev/be/dorothy/member/service/PasswordEncryptorImpl.java
- backend/src/main/java/dev/be/dorothy/member/service/SignUpDto.java
- backend/src/main/java/dev/be/dorothy/member/service/SignUpReqDto.java
- backend/src/test/java/dev/be/dorothy/member/repository/MemberRepositoryTest.java
- backend/src/test/java/dev/be/dorothy/member/service/MemberSignUpValidatorTest.java
- backend/src/test/java/dev/be/dorothy/member/service/PasswordEncryptorImplTest.java
- backend/src/test/resources/application.yml
- backend/src/test/resources/init.sql
- Java 11
- Spring Boot 2.7.8
- MySQL 8.x
- Spring Data Jdbc
- application.yml 사용(.gitignore에 추가)
- Member 도메인 구현
- MemberRepository 생성 후 insert 메서드 구현
- MemberRepositoryTest 생성 후 insert 메서드 테스트
- MemberService 구현
- 회원가입할 때 검증 담당하는 SignUpValidator 구현
- Password 해싱하는 PasswordEncryptor 구현
- 회원가입 요청 데이터를 담는 SignUpReqDto 구현
- 회원가입 후 응답 데이터를 담는 MemberResDto 구현
- 잘못된 요청(400, BAD REQUEST)일 경우 예외인 BadRequestException 구현
- 서버에서 알 수 없는 에러(500, Internal Server Error)가 발생할 경우 예외인 InternalServerErrorException 구현
- 클라이언트에 응답할 때 사용하는 형식인 CommonResponse 구현
- Configuration 어노테이션을 사용하여 PasswordEncryptorImpl 등록하기 위한 AuthConfig 구현
- MemberSignUpValidator 테스트 코드 작성
- PasswordEncryptorImpl 테스트 코드 작성
- Spring Data Jdbc 익숙해지기 위해 공부 목적
- MVC 패턴에 입각하여 책임 분리 원칙을 최대한 만족하기 위한 목적
- Test Coverage를 높임으로써 서비스의 안정성을 보장하기 …
> [#3#4] 백엔드 프로젝트 세팅 및 회원가입 기능 구현

- frontend/index.html
- frontend/src/pages/attendPage.js
- frontend/src/pages/mainPage.js
- frontend/src/pages/noticePage.js
- frontend/src/styles/home.css
일반 사용자 메인 페이지 추가
git 오류로 인한 재작업
mainpage.js html, css 수정
This closes #24
> feature: 일반 사용자 메인 페이지 구성

- backend/src/main/java/dev/be/dorothy/member/controller/MemberController.java
- backend/src/main/java/dev/be/dorothy/member/service/LoginReqDto.java
- backend/src/test/java/dev/be/dorothy/member/controller/MemberControllerTest.java
**Request**
```
POST /member/login
header: {
Content-Type: application/json
}
body: {
"memberId": "lucas",
"password": "a1234567!"
}
```
**Response**
```
header: {
Set-Cookie: [JSESSIONID=52B3C7F17CBE2CDD37628B92BD206A5A; Path=/; HttpOnly]
}
body: {
"idx": 1,
"memberId": "lucas",
"name": "lucas",
"email": "lucas@example.com",
"image": "url",
"createdAt": "2021-08-01T17:07:49.107",
"updatedAt": "2021-08-01T17:07:49.107"
"role": "MEMBER"
}
```
1. 로그인 진행 후, 정상적으로 응답 데이터를 반환하는지 확인하는 테스트 케이스 작성
로그인을 진행하기 위해 클라이언트의 요청을 전달받아 처리하기 위해
1. `MemberService`의 `login`을 사용하여 로그인 처리 진행 및 `MemberResDto` 전달받기
2. 세션 생성 및 결과 클라이언트에 응답하기
컨트롤러 테스트를 위해 `@MockMvc` 및 `@MockBean` 사용
This closes #12
> 로그인 기능 컨트롤러 구현

- backend/src/main/java/dev/be/dorothy/auth/AuthenticationFilter.java
- backend/src/main/java/dev/be/dorothy/auth/AuthorizationFilter.java
- backend/src/main/java/dev/be/dorothy/auth/ContextHolder.java
- backend/src/main/java/dev/be/dorothy/auth/MemberDetail.java
- backend/src/main/java/dev/be/dorothy/auth/MemberDetailService.java
- backend/src/main/java/dev/be/dorothy/auth/SecurityFilter.java
- backend/src/main/java/dev/be/dorothy/auth/authentication/Authentication.java
- backend/src/main/java/dev/be/dorothy/auth/authentication/UsernameAndPasswordToken.java
- backend/src/main/java/dev/be/dorothy/auth/authentication/UsernameAndPasswordTokenProvider.java
- backend/src/main/java/dev/be/dorothy/auth/authorization/AcccessEnum.java
- backend/src/main/java/dev/be/dorothy/auth/authorization/ExpressionUrlAuthorizationConfigurer.java
- backend/src/main/java/dev/be/dorothy/auth/authorization/HttpSecurity.java
- backend/src/main/java/dev/be/dorothy/auth/authorization/SecurityConfig.java
- backend/src/test/java/dev/be/dorothy/auth/SecurityFilterTest.java
SecurityFilter를 구현하여 각 요청이 controller에 도달하기 전 요청을 가로채 session 포함 여부를 파악
SecurityFilter의 doFilter 기능을 테스트하기 위한 테스트 코드 작성
서버 내 리소스 접근 권한을 파악하기 위하여
사용자가 자신이 어떤 사용자 (id) 다라고 주장할 때 그 주장이 맞는지(password) 확인하기 위하여
Filter 인터페이스를 implements하여 컨트롤러 앞 단의 로직을 구현
WebMvc 테스트를 통하여 MockMvc를 주입받아 특정 경로에 대한 Get 리퀘스트를 mocking
This closes #14
> 로그인 세션 관리 기능 구현

- backend/src/main/java/dev/be/dorothy/track/controller/TrackController.java
- backend/src/main/java/dev/be/dorothy/track/service/TrackRegisterServiceImpl.java
- 트랙 생성 API 구현
- 나의 트랙 전체 조회 API 구현
- 트랙 가입 API 구현
사용자가 트랙을 생성하기 위해
사용자가 본인의 트랙 전체를 조회하기 위해
사용자가 트랙에 가입하기 위해
페어 프로그래밍으로 진행.
This closes #59
> 트랙 컨트롤러 구현

- backend/src/main/java/dev/be/dorothy/track/repository/TrackRepository.java
- backend/src/main/java/dev/be/dorothy/track/service/TrackRegisterServiceImpl.java
- backend/src/test/java/dev/be/dorothy/track/repository/TrackRepositoryTest.java
- backend/src/test/java/dev/be/dorothy/track/service/TrackRegisterServiceTest.java
- TrackMember에 중복 데이터 있는 경우 테스트하는 doesExistTrackMemberSuccessTest 코드 작성
- TrackMember에 중복 데이터 없는 경우 테스트하는 doesExistTrackMemberFailTest 코드 작성
- DB의 TrackMember 테이블에 중복 데이터가 있는지 확인하는 메서드 구현
- 트랙에 이미 존재하는 멤버인 경우 400 예외를 던지는지 확인하는 테스트 코드 작성
- 이미 트랙에 가입하고자 하는 멤버가 존재하는 경우 400 예외 던지도록 구현
- Track에 멤버 가입하는 기능에서 DB의 TrackMember 테이블에 중복 데이터 체크를 하기 위해
- 중복 데이터가 있는 경우 400 예외 처리
This closes #65
> Track Member 중복 확인 기능 구현

- frontend/src/pages/rentalDetailPage.js
- frontend/src/pages/rentalPage.js
- frontend/src/router.js
- frontend/src/styles/home.scss
- frontend/src/styles/login.scss
- frontend/src/styles/main.scss
- frontend/src/styles/rental.scss
동적 스크립트 추가 작업 간 발생한 CSS 오류 해결
마크업, SCSS 충돌 오류
마크업, SCSS 내용 일부 변경
This closes #56
> css 깨짐 현상 해결

- frontend/package.json
- frontend/src/apis/http.js
- frontend/src/apis/services/userservice.js
- frontend/src/apis/user.js
- frontend/src/components/calendar/calendar.js
- frontend/src/components/calendar/constants.js
- frontend/src/components/modal.js
- frontend/src/pages/attendPage.js
- frontend/src/pages/homePage.js
- frontend/src/scripts/main.js
- frontend/src/store/user.js
- frontend/src/styles/attend.scss
- frontend/src/styles/home.scss
- 성공 및 실패 모달 퍼블리싱(회원가입, 로그인)
- 트랙 추가 모달 퍼블리싱 (관리자, 일반유저) 
- 퍼블리싱 마무리
This closes #55
> (FE) modal 모달 퍼블리싱

- backend/src/main/java/dev/be/dorothy/track/Track.java
- backend/src/main/java/dev/be/dorothy/track/TrackMember.java
- backend/src/main/java/dev/be/dorothy/track/repository/TrackRepository.java
- backend/src/main/java/dev/be/dorothy/track/service/TrackRegisterServiceImpl.java
- backend/src/test/java/dev/be/dorothy/track/repository/TrackRepositoryTest.java
- backend/src/test/resources/init.sql
- 출석 시간 저장하는 attendanceTime 멤버 변수 추가
- 출석 위치 저장하는 location 멤버 변수 추가
- TrackMember DB에 저장하는 saveTrackMember 메서드 구현
- TrackMember DB 데이터 모두 삭제하는 deleteTrackMember 메서드 구현
위치 기반으로 출석 기능 구현하기 위해
Spring Data Jdbc에서 중간 테이블에 대한 save 기능을 제공하지 않아서 직접 구현
페어 프로그래밍으로 구현
@Query 어노테이션을 통해 직접 쿼리 작성
Spring Data Jdbc에서 Point 타입을 지원하지 않아서 @Embedded 어노테이션 사용
This closes #85
> Track class 수정 및 TrackMember 저장 및 삭제 메서드 구현

- frontend/src/components/main/chart/chart.js
- frontend/src/components/main/chart/currentWeek.js
- frontend/src/components/main/chart/dailyChart.js
- frontend/src/components/main/chart/weeklyChart.js
- frontend/src/components/main/managerMain.js
- frontend/src/components/main/timer/maketimer.js
- frontend/src/components/main/userMain.js
- frontend/src/main.js
- frontend/src/pages/mainPage.js
- frontend/src/scripts/main.js
- frontend/src/styles/chart.scss
- frontend/src/styles/main.scss
- frontend/src/styles/timer.scss
- frontend/src/utils/selector.js
maketimer.js, main.js 동적 코드 수정
setMainEvent 중복호출로 인한 오류 수정
타이머 이벤트 수정, 타이머 CSS 일부 수정
This closes #102
> 타이머 이벤트 오류 수정

- backend/src/main/java/dev/be/dorothy/mapper/PlaceResDtoMapper.java
- backend/src/main/java/dev/be/dorothy/reservation/Place.java
- backend/src/main/java/dev/be/dorothy/reservation/controller/PlaceController.java
- backend/src/main/java/dev/be/dorothy/reservation/repository/PlaceRepository.java
- backend/src/main/java/dev/be/dorothy/reservation/service/PlaceResDto.java
- backend/src/main/java/dev/be/dorothy/reservation/service/PlaceService.java
- backend/src/main/java/dev/be/dorothy/reservation/service/PlaceServiceImpl.java
- backend/src/test/java/dev/be/dorothy/mapper/PlaceResDtoMapperTest.java
- backend/src/test/java/dev/be/dorothy/reservation/repository/PlaceRepositoryTest.java
공유 공간를 나타내는 클래스인 Place 구현
공간에 대한 등록을 진행하기 위한 controller/service/repository 단의 로직 구현
모든 공유 공간에 대한 조회를 진행하기 위한 controller/service/repository 단의 로직 구현
공간 대여 서비스를 구현하기 위한 공유 공간 데이터에 대한 조작을 위하여
하나의 공유 오피스에서 이용하는 공유 공간임을 가정
Dto - Entity 간 변환을 추상화하기 위하여 mapper 인터페이스 구현
'@query' 애노테이션을 이용하여 repository 단에서 dto를 바로 반환하도록 쿼리문 작성
This closes #90, #91
> 공유 공간 등록 및 조회 기능 구현

- frontend/src/apis/user.js
- frontend/src/components/main/profileBox.js
- frontend/src/components/main/userMain.js
- frontend/src/pages/mainPage.js
- frontend/src/styles/attend.scss
- frontend/src/styles/main.scss
메인화면 마크업 수정
메인화면 css 배치 수정 및 최근 공지사항 확인 div 추가
CSS, 동적 HTML 수정
This closes #issueNum
> 메인화면 마크업 수정

- frontend/dist/assets/index-09f76abd.js
- frontend/dist/assets/index-484c70a6.js
- frontend/dist/assets/index-bde115ab.css
- frontend/src/apis/services/userservice.js
- frontend/src/apis/user.js
- frontend/src/components/main/chart/dailyChart.js
- frontend/src/components/main/chart/weeklyChart.js
- frontend/src/components/main/managerMain.js
- frontend/src/components/main/profileBox.js
- frontend/src/components/main/timer/timer.js
- frontend/src/components/main/userMain.js
- frontend/src/components/notice/noticeComponents.js
- frontend/src/pages/mainPage.js
- frontend/src/pages/noticeAddPage.js
- frontend/src/pages/noticeDetailPage.js
- frontend/src/pages/noticePage.js
- frontend/src/router.js
- frontend/src/scripts/main.js
- frontend/src/scripts/rental.js
- frontend/src/styles/attend.scss
- frontend/src/styles/chart.scss
- frontend/src/styles/main.scss
- frontend/src/styles/notice.scss
- frontend/src/styles/timer.scss
- 공지사항 상세 페이지 퍼블리싱
- 공지사항 기능 추가에 따른 필요한 페이지 퍼블리싱
This closes #105
> 공지사항 상세 페이지 퍼블리싱

- frontend/src/apis/http.js
- frontend/src/apis/services/trackservices.js
- frontend/src/apis/services/userservice.js
- frontend/src/apis/track.js
- frontend/src/apis/user.js
- frontend/src/components/main/managerMain.js
- frontend/src/components/main/profileBox.js
- frontend/src/components/main/timer/maketimer.js
- frontend/src/components/main/timer/timer.js
- frontend/src/components/rental/placeCard.js
- frontend/src/components/track/trackCard.js
- frontend/src/main.js
- frontend/src/pages/mainPage.js
- frontend/src/scripts/home.js
- frontend/src/scripts/main.js
- frontend/src/scripts/rental.js
- frontend/src/styles/main.scss
- frontend/src/styles/rental.scss
- frontend/src/styles/rentalDetail.scss
- frontend/src/utils/selector.js
- frontend/vite.config.js
- 로그인 모달 수정
- 로그인 메인페이지 이동 제한
- 권한 제한 필요
This closes #122
> 로그인 페이지 이동 제한

- .github/workflows/dev.yml
- scripts/back-deploy.sh
- scripts/front-build.sh
프론트, 백엔드 통합 배포 스크립트 작성
프론트와 백엔드의 개발이 완료된 후, dev 브랜치로 머지 되었을 때 자동으로 배포를 진행하기 위하여
> 아직 작성 미완료.. 추가로 작성 예정
This closes #23
> 프론트, 백엔드 통합 배포 스크립트 작성

- backend/src/main/java/dev/be/dorothy/common/scheduler/ExampleScheduler.java
- backend/src/main/java/dev/be/dorothy/config/SchedulerConfig.java
- `SchedulerConfig` 작성
- `ExampleScheduler` 작성
- `SchedulerConfig` -> 기본적으로 스프링 스케줄러는 싱글 스레드로 동작한다. 따라서 `pool size`를 10으로 설정하고 멀티 쓰레드로 동작할 수 있도록 구성
- `ExampleScheduler` -> 실제 스케줄러를 사용하기 위한 기본적은 예제
- `SchedulerConfig`
- `SpringFramework`에  내장되어있는 `scheduling` 패키지를 활용하여 구현
- 최대 `pool size`를 10으로 설정
- `ExampleScheduler`
-  2초 마다 현재 시간을 로깅하도록 구현 
[cron 적용](https://wooncloud.tistory.com/75)
This closes #111
> 스프링 스케줄러 기본 틀 구현

- backend/src/main/java/dev/be/dorothy/security/ExceptionHandlerFilter.java
- backend/src/main/java/dev/be/dorothy/security/authorization/AcccessEnum.java
- backend/src/main/java/dev/be/dorothy/security/authorization/ExpressionUrlAuthorizationConfigurer.java
- backend/src/main/java/dev/be/dorothy/security/authorization/HttpSecurity.java
- backend/src/main/java/dev/be/dorothy/security/authorization/SecurityConfig.java
- backend/src/main/java/dev/be/dorothy/security/filter/AuthenticationFilter.java
- backend/src/main/java/dev/be/dorothy/security/filter/AuthorizationFilter.java
- backend/src/main/java/dev/be/dorothy/security/filter/LoginFilter.java
AuthorizationFilter의 doFilter 메소드 구현
ExceptionHandlerFilter 클래스 생성
AccessEnum의 추상 메소드 수정
로그인과 회원가입을 제외한 모든 요청에 대해 로그인을 요구하기 위해
필터 상에서 발생하는 exception을 일괄적으로 핸들링하기 위해
ExceptionHandlerFilter의 order를 1로 정하여 이후의 모든 필터에서 발생하는 exception을 핸들링하여 http response 메시지를 작성함
SecurityConfig의 httpSecurity 설정에서 모든 경로에 대한 요청에 대해 isAuthenticated를 부여하여 로그인 헀을 때만 이용할 수 있도록 함.
This closes #124
> 사용자 권한 기반 리소스에 대한 접근 관리 구현

- backend/src/main/java/dev/be/dorothy/attendance/controller/AttendanceController.java
- backend/src/main/java/dev/be/dorothy/attendance/repository/AttendanceRepository.java
- backend/src/main/java/dev/be/dorothy/attendance/service/AttendanceManagerService.java
- backend/src/main/java/dev/be/dorothy/attendance/service/AttendanceManagerServiceImpl.java
- backend/src/main/java/dev/be/dorothy/attendance/service/AttendanceReqDto.java
- backend/src/main/java/dev/be/dorothy/attendance/service/AttendanceResDto.java
- backend/src/main/java/dev/be/dorothy/attendance/service/AttendanceRetrieveResDto.java
- backend/src/main/java/dev/be/dorothy/attendance/service/AttendanceRetrieveService.java
- backend/src/main/java/dev/be/dorothy/attendance/service/AttendanceRetrieveServiceImpl.java
- backend/src/main/java/dev/be/dorothy/attendance/service/AttendanceService.java
- backend/src/main/java/dev/be/dorothy/attendance/service/AttendanceServiceImpl.java
- backend/src/main/java/dev/be/dorothy/mapper/AttendanceResDtoMapper.java
- backend/src/main/java/dev/be/dorothy/track/service/TrackRetrieveService.java
- backend/src/main/java/dev/be/dorothy/track/service/TrackRetrieveServiceImpl.java
- backend/src/test/java/dev/be/dorothy/attendance/service/AttendanceManagerServiceImplTest.java
- backend/src/test/java/dev/be/dorothy/attendance/service/AttendanceServiceImplTest.java
- backend/src/test/java/dev/be/dorothy/mapper/AttendanceResDtoMapperTest.java
- 출석 요청 시간에 따른 출결 상태 확인하는 기능의 메서드 테스트하는 코드 작성
- 출석 요청 시간에 따른 출결 상태를 확인하기 위한 checkAttendanceTime 메서드 구현
- TrackRetrieveServiceImpl에 getTrackMemberIdx 메서드 구현
- AttendanceServiceImplTest 코드 작성
- AttendanceReqDto 구현
- AttendanceResDtoMapper 구현
- AttendanceServiceImpl 구현
- 당일이 아닌 다른 날짜로 출석 요청하는 경우, 예외 처리
- 중복된 출석 요청이 오는 경우, 예외 처리
- 출석 요청 처리하는 attend 메서드 구현
- 사용자 별로 당일 출결 현황 조회하는 readAttendanceByDay 메서드 구현
- Member가 당일 출결 현황을 조회할 때 사용하는 getAttendanceByDayWhenMember 메서드 구현
- Admin이 트랙에 속한 멤버들의 당일 출결 현황을 조회할 때 사용하는 getAttendanceByDayWhenAdmin 메서드 구현
- Member가 당일 출결 현황을 조회할 때 사용하는 retrieveAttendanceByDayWhenMember 메서드 구현
- Admin이 트랙에 속한 멤버들의 당일 출결 현황을 조회할 때 사용하는 retrieveAttendanceByDayWhenAdmin 메서드 구현
- 출석 요청 시간에 따라 출결 상태를 판단하기 위해
- Service 단에서 출석 기능을 구현하고, 해당 정보를 DB에 저장하기 위해
- 사용자의 당일 출결 현황을 조회하기 …
> checkAttendanceTime 메서드, AttendanceService, AttendanceController, AttendanceRepository, AttendanceRetrieveService 구현

- frontend/index.html
- frontend/src/apis/user.js
- frontend/src/components/home/loginForm.js
- frontend/src/components/home/registerForm.js
- frontend/src/scripts/home.js
- frontend/src/scripts/main.js
- frontend/src/styles/login.scss
첫 화면 완료
로그인/회원가입 폼 입력 칸 비어있으면 버튼 비활성화
로그인/회원가입 토글 시 입력 내용 비움
로그인 성공할 시 화면 전환
login.scss, home.scss, home.js, user.js 수정
This closes #138
> 로그인/회원가입 화면 완성

- frontend/src/apis/services/trackservices.js
- frontend/src/apis/track.js
- frontend/src/apis/user.js
- frontend/src/components/dice/dice.js
- frontend/src/components/main/managerMain.js
- frontend/src/components/main/profileBox.js
- frontend/src/components/main/timer/timer.js
- frontend/src/components/track/addTrack.js
- frontend/src/components/track/trackCard.js
- frontend/src/pages/mainPage.js
- frontend/src/pages/trackPage.js
- frontend/src/scripts/main.js
- frontend/src/store/user.js
- frontend/src/styles/main.scss
- frontend/src/styles/timer.scss
- frontend/src/styles/track.scss
#136
- 트랙 추가 기능 구현
- 트랙 관련 기능 구현 필요
This closes #136
> 트랙 추가 기능 구현

- frontend/src/apis/attend.js
- frontend/src/apis/notice.js
- frontend/src/apis/services/attendservices.js
- frontend/src/apis/services/noticeservices.js
- frontend/src/apis/services/trackservices.js
- frontend/src/apis/services/userservice.js
- frontend/src/components/calendar/calendar.js
- frontend/src/components/main/chart/currentWeek.js
- frontend/src/components/main/chart/dailyChart.js
- frontend/src/components/main/chart/weeklyChart.js
- frontend/src/components/main/profileBox.js
- frontend/src/components/main/timer/maketimer.js
- frontend/src/components/main/userMain.js
- frontend/src/components/notice/noticeComponents.js
- frontend/src/main.js
- frontend/src/pages/mainPage.js
- frontend/src/pages/noticeDetailPage.js
- frontend/src/pages/noticePage.js
- frontend/src/router.js
- frontend/src/scripts/main.js
- frontend/src/scripts/notice.js
- frontend/src/styles/attend.scss
- frontend/src/styles/main.scss
- frontend/src/styles/notice.scss
- 일간 출석 차트 기능 구현
- 메인 페이지 오류 수정 (관리자 및 일반 유저)
- 일반 유저 메인 페이지 최근 공지사항 반영 => 클릭시 상세페이지로 이동
This closes #150
> 메인페이지 및 공지사항 기능 구현

- frontend/src/apis/rental.js
- frontend/src/apis/services/rentalServices.js
- frontend/src/apis/services/trackservices.js
- frontend/src/apis/track.js
- frontend/src/components/main/profileBox.js
- frontend/src/components/rental/hourCard.js
- frontend/src/components/track/trackCard.js
- frontend/src/main.js
- frontend/src/pages/rentalPage.js
- frontend/src/pages/trackPage.js
- frontend/src/scripts/main.js
- frontend/src/scripts/rental.js
- frontend/src/scripts/rentalDetail.js
- frontend/src/styles/main.scss
- frontend/src/styles/rentalDetail.scss
공간 조회 기능, 대여 시간대 조회 기능, 공간 대여 신청 기능 추가
서버 연동하여 공간 조회
rental.js, rentalDetail.js 수정
This closes #161
> 공간 대여 통신 추가

- backend/src/main/java/dev/be/dorothy/attendance/controller/AttendanceController.java
- backend/src/main/java/dev/be/dorothy/attendance/repository/AttendanceRepository.java
- backend/src/main/java/dev/be/dorothy/attendance/service/AttendanceRetrieveService.java
- backend/src/main/java/dev/be/dorothy/attendance/service/AttendanceRetrieveServiceImpl.java
- backend/src/main/java/dev/be/dorothy/attendance/service/AttendanceStatisticsResDto.java
- ADMIN이 트랙에 속한 멤버들의 월간 출결 현황을 조회하는 기능 수정
- 출결에 대한 통계를 내기 위해
- 몇 일에 출석 몇 명, 지각 몇 명, 결석 몇 명인지에 대한 데이터를 응답하는 방식으로 수정
This closes #164
> ADMIN이 월간 출결 현황 조회하는 기능 수정

- frontend/.gitignore
- frontend/src/components/main/timer/timer.js
- frontend/src/main.js
- frontend/src/pages/attendPage.js
- frontend/src/styles/main.scss
- frontend/src/styles/timer.scss
- 출석 페이지 관리자 / 일반 유저 구분 
This closes #163
> 출석 페이지 관리자 일반 유저 구분 

- backend/src/main/java/dev/be/dorothy/reservation/service/PlaceReservationManagerImpl.java
- backend/src/main/java/dev/be/dorothy/reservation/service/PlaceReservationServiceImpl.java
- backend/src/main/java/dev/be/dorothy/reservation/service/ReservationResDto.java
ReservationResDto 클래스 수정
Front-end 와의 협업 시 필드 명을 맞추기 위해
예약 시간 출력 형식을 "hh:MM:ss" 에서 "hh:MM"으로 변경
This closes #170
> 공간 예약 코드 리팩토링

- backend/src/main/java/dev/be/dorothy/security/filter/LogoutFilter.java
SecurityFilter 패키지 내 logoutFilter 클래스 작성
JSESSIONID를 이용한 세션을 삭제시키면서 로그아웃을 처리하기 위하여
logout 요청을 가로채어 유저의 쿠키를 삭제하고 세션을 만료시키는 로직 작성
This closes #173
> LogoutFilter 구현

- frontend/src/apis/http.js
- frontend/src/apis/track.js
- frontend/src/components/calendar/calendar.js
- frontend/src/components/main/chart/dailyChart.js
- frontend/src/components/main/chart/weeklyChart.js
- frontend/src/components/main/profileBox.js
- frontend/src/components/main/timer/maketimer.js
- frontend/src/components/main/userMain.js
- frontend/src/components/track/trackCard.js
- frontend/src/pages/attendPage.js
- frontend/src/pages/homePage.js
- frontend/src/scripts/main.js
- frontend/src/store/user.js
- frontend/src/styles/rental.scss
- 스토어 트랙 아이디 저장
- 스토어 트랙 아이디 저장
- 스토어 트랙 아이디 저장
> 스토어 트랙 아이디 저장
